### ISSUE TITLE
Thread Panic with trailing slash in path

### ISSUE THREAD

**Issue by Benzammour** [m1guelperez/virustotal-CLI#1]
After running the binary in Powershell, using a string in quotation marks as the path argument due to the space in the username, the result was not the expected one.
The thread panics and hints us to use the appropriate flags when running the binary.
My guess would be that the quotation marks are escaped by the trailing backslash which is not caught properly.

Command:
```PS C:\Users\S B\Desktop> .\virustotal_folderscanner.exe 'C:\Users\S B\Desktop\' -p```

Output:
```["C:\\Users\\S B\\Desktop\\virustotal_folderscanner.exe", "C:\\Users\\S B\\Desktop\" -p"]
Commands length: 2
thread 'main' panicked at 'You have to provide either the '-u' or '-p' flag.', src\user_input.rs:46:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by m1guelperez** [comment]
Thanks Samir, for testing my application issue.

I could reproduce this behavior and I am currently working on a fix.

**Comment by m1guelperez** [comment]
The issue has been fixed. It was more or less a problem with PowerShell rather than Rust. For example, when using Powershell 7.2 the problem won't occur.

However, I added a function, to catch arguments, which haven't been escaped properly in older PowerShell versions.
